ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of higgsCP_UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_13 = ', GC_13
      WRITE(*,2) 'GC_14 = ', GC_14
      WRITE(*,2) 'GC_15 = ', GC_15
      WRITE(*,2) 'GC_16 = ', GC_16
      WRITE(*,2) 'GC_17 = ', GC_17
      WRITE(*,2) 'GC_18 = ', GC_18
      WRITE(*,2) 'GC_19 = ', GC_19
      WRITE(*,2) 'GC_32 = ', GC_32
      WRITE(*,2) 'GC_34 = ', GC_34
      WRITE(*,2) 'GC_35 = ', GC_35
      WRITE(*,2) 'GC_36 = ', GC_36
      WRITE(*,2) 'GC_37 = ', GC_37
      WRITE(*,2) 'GC_38 = ', GC_38
      WRITE(*,2) 'GC_40 = ', GC_40
      WRITE(*,2) 'GC_41 = ', GC_41
      WRITE(*,2) 'GC_44 = ', GC_44
      WRITE(*,2) 'GC_52 = ', GC_52
      WRITE(*,2) 'GC_54 = ', GC_54
      WRITE(*,2) 'GC_56 = ', GC_56
