ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' Couplings of higgsCP_UFO'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,2) 'GC_13 = ', GC_13
      WRITE(*,2) 'GC_32 = ', GC_32
      WRITE(*,2) 'GC_34 = ', GC_34
      WRITE(*,2) 'GC_35 = ', GC_35
      WRITE(*,2) 'GC_36 = ', GC_36
      WRITE(*,2) 'GC_37 = ', GC_37
      WRITE(*,2) 'GC_38 = ', GC_38
      WRITE(*,2) 'GC_39 = ', GC_39
      WRITE(*,2) 'GC_41 = ', GC_41
      WRITE(*,2) 'GC_44 = ', GC_44
      WRITE(*,2) 'GC_45 = ', GC_45
      WRITE(*,2) 'GC_46 = ', GC_46
      WRITE(*,2) 'GC_47 = ', GC_47
      WRITE(*,2) 'GC_48 = ', GC_48
      WRITE(*,2) 'GC_49 = ', GC_49
      WRITE(*,2) 'GC_50 = ', GC_50
      WRITE(*,2) 'GC_52 = ', GC_52
      WRITE(*,2) 'GC_54 = ', GC_54
      WRITE(*,2) 'GC_56 = ', GC_56
